"""Project file templates rendered with `string.Template`.

Everything wheelforge generates lives here as a single source of truth. The
templates deliberately use `$name` placeholders rather than f-strings so the
file bodies stay readable as the Python and TOML they will become.

Two launcher layouts are supported, and they shape the whole generated project:

`direct`
    The executable is staged outside the module and mapped into the wheel's
    `.data/scripts/` directory, so installers place the real binary straight
    onto `PATH`. There is no `[project.scripts]` entry, because a console
    script of the same name would overwrite the binary on install.

`shim`
    The executable lives inside the package at `bin/`, and a `[project.scripts]`
    entry point runs `__main__.main`, which `execv`s it. Costs one interpreter
    start per invocation but keeps everything inside the importable package.
"""

import json
from string import Template
from typing import Final

PYPROJECT: Final[Template] = Template(
    """\
# Generated by wheelforge. Do not edit by hand -- regenerate instead.
[build-system]
requires = ["uv_build>=0.11.30,<0.12"]
build-backend = "uv_build"

[project]
name = $name
version = $version
description = $description
requires-python = $requires_python
readme = "README.md"
dependencies = []
$project_extra$scripts_table$urls_table
[tool.uv.build-backend]
module-name = "$module"
module-root = "src"
$data_table"""
)

#: Staged outside the module so the binary is not also swept into the wheel as
#: package data, which would embed a second copy of it.
DATA_TABLE: Final[Template] = Template(
    """\

# Maps the staged executable into the wheel's `.data/scripts/` directory.
# Installers copy it straight onto PATH, so no Python runs on invocation.
[tool.uv.build-backend.data]
scripts = "$scripts_dir"
"""
)

_INIT_HEADER: Final[str] = '''\
"""$dist_name -- $binary_name packaged as a Python wheel by wheelforge."""

$imports
__version__ = "$version"
__all__ = ["__version__", "binary_path", "BINARY_NAME"]

#: File name of the bundled program -- a binary, or a script with a `#!`.
BINARY_NAME = "$binary_name"
'''

INIT_SHIM: Final[Template] = Template(
    _INIT_HEADER
    + '''

def binary_path():
    """Absolute path to the bundled `$binary_name`.

    Useful for invoking the tool from Python without going through the console
    script, e.g. `subprocess.run([str(binary_path()), "--version"])`.
    """
    return Path(__file__).resolve().parent / "bin" / BINARY_NAME
'''
)

INIT_DIRECT: Final[Template] = Template(
    _INIT_HEADER
    + '''

def binary_path():
    """Absolute path to the bundled `$binary_name`.

    It is installed into the environment's scripts directory rather
    than into this package, so it has to be located rather than computed.

    Locations beside this package are checked first because they are derived
    from where this package actually sits. `sysconfig` describes the running
    interpreter instead, which is the wrong answer under
    `pip install --target`: it would point at the interpreter's own scripts
    directory, and any same-named tool there would be picked up by mistake.
    """
    scripts = sysconfig.get_path("scripts")
    beside = Path(__file__).resolve().parent.parent
    candidates = [
        beside / "bin" / BINARY_NAME,
        beside / "Scripts" / BINARY_NAME,
        Path(scripts) / BINARY_NAME if scripts else None,
    ]
    for candidate in candidates:
        if candidate is not None and candidate.is_file():
            return candidate
    raise FileNotFoundError(
        "could not locate the bundled program "
        + repr(BINARY_NAME)
        + "; looked in "
        + ", ".join(repr(str(c)) for c in candidates if c is not None)
    )
'''
)

MAIN: Final[Template] = Template(
    '''\
"""Console entry point: hand control to the bundled `$binary_name`."""

import os
import sys

from . import BINARY_NAME, binary_path


def main():
    """Replace this process with the bundled program.

    On POSIX this is an `execv`, so signals, exit codes and terminal control
    transfer to the real tool with no Python process left in the middle.
    Windows has no real `exec`, so there we wait on a child process instead.
    """
    try:
        exe = binary_path()
    except FileNotFoundError as exc:
        sys.stderr.write("$dist_name: " + str(exc) + "\\n")
        return 1

    # Refuse to exec ourselves. If resolution ever picks up this very script
    # the exec would repeat forever, hanging the terminal rather than failing.
    script = sys.argv[0]
    if script and os.path.exists(script) and os.path.samefile(str(exe), script):
        sys.stderr.write(
            "$dist_name: refusing to exec self at " + str(exe) + "; the bundled "
            "program could not be told apart from this launcher\\n"
        )
        return 1

    argv0 = os.path.basename(sys.argv[0]) or BINARY_NAME
    args = [argv0] + sys.argv[1:]

    if os.name == "nt":
        import subprocess

        return subprocess.run([str(exe)] + sys.argv[1:]).returncode

    try:
        os.execv(str(exe), args)
    except PermissionError:
        # Some installers strip the executable bit; restore it and retry once.
        exe.chmod(0o755)
        os.execv(str(exe), args)
    return 0  # unreachable: execv never returns on success


if __name__ == "__main__":
    sys.exit(main())
'''
)

#: What the launcher means to somebody installing the package, rather than what
#: it is called. The name alone is wheelforge's jargon, and this text ends up
#: on a PyPI project page.
LAUNCHER_NOTES: Final[dict[str, str]] = {
    "direct": (
        "That is the program itself rather than a Python wrapper around it, so "
        "invoking it starts no interpreter and costs nothing in startup time."
    ),
    "shim": (
        "That is a small Python launcher, which hands over to the bundled "
        "program with `execv` — signals, exit codes and terminal control all "
        "pass straight through to it."
    ),
}

#: Opening of the README's provenance section. Two of them, because a project
#: publishing one wheel and a project publishing eleven are describing
#: genuinely different things, and PyPI renders whichever wheel's description
#: it happens to pick as the page for the whole project.
PROVENANCE_INTROS: Final[dict[str, str]] = {
    "solo": (
        "This wheel repackages a program somebody else built. wheelforge does "
        "not compile or modify it, so what is inside the wheel is exactly what "
        "it was handed — and the digest below is there to be checked against "
        "whatever the tool's own publisher lists."
    ),
    "set": (
        "These wheels repackage a program somebody else built. wheelforge "
        "does not compile or modify it, so what is inside each wheel is "
        "exactly what it was handed — and the digests below are there to be "
        "checked against whatever the tool's own publisher lists. One wheel is "
        "published per platform; your installer picks the one matching your "
        "machine."
    ),
}

README: Final[Template] = Template(
    """\
# $dist_name

`$binary_name` packaged as a Python wheel, so it can be installed with any
Python package manager:

```zsh
uv tool install $dist_name@latest
# or
pipx install $dist_name
# or
pip install $dist_name
```

That puts $alias_list on your `PATH`.
$launcher_note

It is also reachable from Python, which is useful for calling the tool from a
script without going through `PATH`:

```python
from $module import binary_path

print(binary_path())
```

## Provenance

$provenance_intro

$provenance_facts
$tag_note
Generated by [wheelforge][wf], which does not vouch for the program it
packages. Check the upstream licence before redistributing it further.

[wf]: https://github.com/krishdesai7/wheelforge
"""
)


def toml_str(value: str) -> str:
    """Render a Python string as a TOML basic string.

    TOML's basic-string escapes are a subset of JSON's, so `json.dumps` gives a
    correct (and safely escaped) result for the values emitted.
    """
    return json.dumps(value)


def toml_array(values: list[str]) -> str:
    return "[" + ", ".join(toml_str(v) for v in values) + "]"
