"""Project file templates rendered with `string.Template`.

Everything wheelbarrow generates lives here as a single source of truth. The
templates deliberately use `$name` placeholders rather than f-strings so the
file bodies stay readable as the Python and TOML they will become.
"""

import json
from string import Template
from typing import Final

PYPROJECT: Final[Template] = Template(
    """\
# Generated by wheelbarrow. Do not edit by hand -- regenerate instead.
[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = $name
version = $version
description = $description
requires-python = $requires_python
readme = "README.md"
dependencies = []
$project_extra
[project.scripts]
$scripts
$urls_table
# `packages` includes every file under the package directory, which is what
# carries the staged executable in `bin/` into the wheel.
[tool.hatch.build.targets.wheel]
packages = ["src/$module"]
"""
)

INIT: Final[Template] = Template(
    '''\
"""$dist_name -- $binary_name packaged as a Python wheel by wheelbarrow."""

from __future__ import annotations

from pathlib import Path

__version__ = "$version"
__all__ = ["__version__", "binary_path", "BINARY_NAME"]

#: File name of the bundled executable inside this package's `bin/` directory.
BINARY_NAME = "$binary_name"


def binary_path() -> Path:
    """Absolute path to the bundled `$binary_name` executable.

    Useful for invoking the tool from Python without going through the console
    script, e.g. `subprocess.run([str(binary_path()), "--version"])`.
    """
    return Path(__file__).resolve().parent / "bin" / BINARY_NAME
'''
)

MAIN: Final[Template] = Template(
    '''\
"""Console entry point: hand control to the bundled `$binary_name`."""

from __future__ import annotations

import os
import sys
from pathlib import Path

BINARY_NAME = "$binary_name"


def binary_path() -> Path:
    """Absolute path to the bundled executable."""
    return Path(__file__).resolve().parent / "bin" / BINARY_NAME


def main() -> int:
    """Replace this process with the bundled binary.

    On POSIX we `execv`, so signals, exit codes and terminal control transfer
    to the real tool with no Python process left in the middle. Windows has no
    real `exec`, so there we wait on a child process instead.
    """
    exe = binary_path()
    if not exe.exists():
        sys.stderr.write(
            f"$dist_name: bundled executable is missing at {exe}\\n"
            "The wheel may have been installed for the wrong platform.\\n"
        )
        return 1

    argv0 = os.path.basename(sys.argv[0]) or BINARY_NAME
    args = [argv0, *sys.argv[1:]]

    if os.name == "nt":
        import subprocess

        return subprocess.run([str(exe), *sys.argv[1:]]).returncode

    try:
        os.execv(str(exe), args)
    except PermissionError:
        # Some installers strip the executable bit; restore it and retry once.
        try:
            exe.chmod(0o755)
        except OSError:
            raise
        os.execv(str(exe), args)
    return 0  # unreachable: execv never returns on success


if __name__ == "__main__":
    sys.exit(main())
'''
)

README: Final[Template] = Template(
    """\
# $dist_name

`$binary_name` packaged as a Python wheel, so it can be installed with any
Python package manager:

```console
uv tool install $dist_name
# or
pipx install $dist_name
# or
pip install $dist_name
```

That puts $alias_list on your `PATH`.

The executable is also reachable from Python:

```python
from $module import binary_path

print(binary_path())
```

## Provenance

This wheel was generated by [wheelbarrow][wb] from a prebuilt `$binary_name`
binary. It targets `$platform_tag`. wheelbarrow does not compile or modify the
binary; it only repackages it.

[wb]: https://github.com/krishdesai7/wheelbarrow
"""
)


def toml_str(value: str) -> str:
    """Render a Python string as a TOML basic string.

    TOML's basic-string escapes are a subset of JSON's, so `json.dumps` gives a
    correct (and safely escaped) result for the values emitted.
    """
    return json.dumps(value)


def toml_array(values: list[str]) -> str:
    return "[" + ", ".join(toml_str(v) for v in values) + "]"
